package com.example.manager;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.ImageView;
import android.widget.TextView;

import com.example.manager.models.Complaint;
import com.transferwise.sequencelayout.SequenceStep;

import org.parceler.Parcels;

public class ComplaintDetails extends AppCompatActivity {

    TextView complaintId, date, cost, model, machineType, mechanic, serviceType, description, instruction, status;
    ImageView chat;
    SequenceStep sequenceStep1,sequenceStep2,sequenceStep3,sequenceStep4,sequenceStep5;
    String generatedDate, mechanicUserName, completedDate;
    int complaintStatus;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_complaint_details);

        complaintId = findViewById(R.id.complaint_id);
        date = findViewById(R.id.generated_date);
        cost = findViewById(R.id.cost);
        machineType = findViewById(R.id.textView3);
        model = findViewById(R.id.model_number);
        mechanic = findViewById(R.id.mechanic_user_name);
        serviceType = findViewById(R.id.service_type);
        description = findViewById(R.id.complaint_description);
        instruction = findViewById(R.id.instructions);
        status = findViewById(R.id.status);
        chat = findViewById(R.id.chat);

        final Complaint complaint = Parcels.unwrap(getIntent().getParcelableExtra("complaint"));

        complaintId.setText(String.valueOf(complaint.getComplaintId()));
        date.setText(complaint.getGeneratedDate());
        cost.setText(String.valueOf(complaint.getMachine().getPrice()));
        machineType.setText(complaint.getMachine().getType());
        model.setText(complaint.getMachine().getModelNumber());
        mechanic.setText(complaint.getMechanic().getUserName());
        serviceType.setText(complaint.getServiceType());
        description.setText(complaint.getDescription());
        instruction.setText(complaint.getInstruction());
        if (complaint.getStatus() == 5)
            status.setText("completed");
        else
            status.setText("pending");

        chat.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {

                Intent intent = new Intent(getApplicationContext(), ChatActivity.class);
                intent.putExtra("userid", complaint.getMechanic().getUid());
                intent.putExtra("complaintId", String.valueOf(complaint.getComplaintId()));
                intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
                startActivity(intent);
            }
        });

        sequenceStep1=findViewById(R.id.step1);
        sequenceStep2=findViewById(R.id.step2);
        sequenceStep3=findViewById(R.id.step3);
        sequenceStep4=findViewById(R.id.step4);
        sequenceStep5=findViewById(R.id.step5);

        if (complaint != null) {
            complaintStatus = complaint.getStatus();
            generatedDate = complaint.getGeneratedDate();
            mechanicUserName = complaint.getMechanic().getUserName();
            completedDate = "default";
        }




        sequenceStep1.setAnchor(generatedDate);

        if(complaintStatus == 2)
        {
            sequenceStep2.setActive(true);
            sequenceStep2.setAnchor("today");
            sequenceStep2.setTitleTextAppearance(R.style.Title);
            sequenceStep2.setSubtitle("complaint is assigned to "+ mechanicUserName);
            sequenceStep2.setSubtitleTextAppearance(R.style.subTitle);

        }
        else if(complaintStatus == 3)
        {
            sequenceStep3.setActive(true);

            sequenceStep3.setAnchor("today");
            sequenceStep3.setTitleTextAppearance(R.style.Title);
            sequenceStep3.setSubtitle("request has been generated by "+ mechanicUserName);
            sequenceStep3.setSubtitleTextAppearance(R.style.subTitle);
        }
        else if(complaintStatus == 5)
        {
            sequenceStep5.setActive(true);
            sequenceStep5.setTitleTextAppearance(R.style.Title);
            sequenceStep5.setAnchor(completedDate);

        }

    }
}
